name: emergesense
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_sound: ^9.5.0
  flutter_sound_record_platform_interface: ^0.3.1
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
